# Generated by Django 5.0.7 on 2024-07-29 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogers.bloger')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
