# Generated by Django 5.0.7 on 2024-07-30 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogers', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogers.post'),
            preserve_default=False,
        ),
    ]
